blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/adam-rho/accessible-react-form/discussions
    about: For questions and open-ended discussion, use Discussions instead of Issues.
